# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "R M Purushoth Kumar"
email: purushoth.iitkgp@gmail.com
description: >-
  Senior Applied Data Scientist | ML Engineer | Visual Storyteller
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username: purushoth-kumar

# Build settings
remote_theme: "daattali/beautiful-jekyll@5.0.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

# Beautiful Jekyll specific settings
avatar-img: /assets/images/forty.jpg
title-img: /assets/images/forty.jpg
subtitle: "Senior Applied Data Scientist"
description: "Transforming data into actionable insights through advanced analytics, machine learning, and causal inference. Passionate about building recommendation systems and driving product decisions with data."

# Author settings
author: "Purushoth Kumar"
author-title: "Senior Applied Data Scientist"
author-location: "India"
author-email: "purushoth.iitkgp@gmail.com"
author-avatar: "/assets/images/forty.jpg"
author-bio: "Data Scientist passionate about ML, AI, and data visualization."

# Social media
social-network-links:
  github: purushoth-kumar
  linkedin: purushothkumar
  email: purushoth.iitkgp@gmail.com

# Navigation
navbar-links:
  About Me: "about"
  Projects: "projects"
  Resume: "resume_purushoth.pdf"

# Theme settings
navbar-color: dark
sidebar-color: dark
footer-color: dark

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Remove recent posts from homepage by setting show_excerpts: false and removing related config
show_excerpts: false

include:
  - assets/css/custom.css
