# Minimal Mistakes theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site settings
title: "<i class='fa fa-home'></i>"
email: youremailaddress@gmail.com
description: "Data Scientist | ML Engineer | Visual Storyteller"
url: "https://purushoth-kumar.github.io"
baseurl: "" # leave blank for user/organization site

# Author settings
author:
  name: "Purushoth Kumar"
  avatar: "/assets/images/forty.jpg" # update with your photo if available
  bio: "Data Scientist passionate about ML, AI, and data visualization."
  location: "India"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/purushoth-kumar"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/purushothkumar"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# Plugins (GitHub Pages safe)
plugins:
  - jekyll-remote-theme
#  - jekyll-feed  # Disabled to remove feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Markdown and syntax highlighting
markdown: kramdown
highlighter: rouge

# Exclude old theme settings
# (Removed tiles-source, tiles-count, and old social settings)

# Social sharing
social:
  name: "Purushoth Kumar"
  links:
    - "https://github.com/purushoth-kumar"
    - "https://www.linkedin.com/in/purushothkumar"

custom_css:
  - /assets/css/custom.css
